//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDD_API.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car_Colors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car_Colors()
        {
            this.Cars = new HashSet<Car>();
        }
    
        public string Color_num { get; set; }
        public string Color_code { get; set; }
        public string name { get; set; }
        public string Colorname { get; set; }
        public Nullable<int> is_metallic_ { get; set; }
        public string Name_EN { get; set; }
        public string Colorname_EN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Car> Cars { get; set; }
    }
}
