//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDD_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public string VIN { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> weight { get; set; }
        public string Number_of_color { get; set; }
        public Nullable<int> Engine_type { get; set; }
        public string type_of_drive { get; set; }
        public string category_of_car { get; set; }
        public Nullable<int> Engine_number { get; set; }
        public Nullable<int> Engine_year { get; set; }
        public Nullable<int> Engine_power_kvt { get; set; }
        public Nullable<int> Engine_pover_l_c_ { get; set; }
        public Nullable<int> Max_weight { get; set; }
        public string Engine_model { get; set; }
        public Nullable<int> driver { get; set; }
    
        public virtual Car_Colors Car_Colors { get; set; }
        public virtual Driver Driver1 { get; set; }
    }
}
